FORMAT: 1A
HOST: https://onboarding.example.org

# Onboarding API

This is a preliminary sketch of the Onboarding API

## Home [/]

### Get Home Resource [GET]

+ Response 200 (text/html)

            <h1>Home</h1>

### Create Onboarding Record [POST]

+ Request (application/x-www-form-urlencoded)

            onboardingId=1q2w3e4r5t

+ Response 201 (text/html)

    + Header
    
            Location: /1q2w3e4r5t
            
    + Body

            <p><a href="/1q2w3e4r5t">created ITEM:1q2w3e4r5t</a></p>

## Onboarding Create Form [/create]

### Show Onboarding Create Form [GET]

+ Response 200 (text/html)

        <h1>CREATE-FORM</h1>
        <form name="create" action="/list" method="post">
            onboardingId:<input name="onboardingId" value="1q2w3e4r5t" />
            <input type="submit" />
        </form>
        
        
## Show Record [/record]
### Show Onboarding Record [GET]

    + Body

            Onboarding Record [/1q2w3e4r5t]

+ Response 200 (text/html)

        <h1>ITEM:1q2w3e4r5t</h1>
        
        <p><a href="/list">LIST</a></p>
        
        <p>data fields display here...</p>
        
        <p><a href="/1q2w3e4r5t/company">Show Company Info Form</a></p>
        
        <p><a href="/1q2w3e4r5t/account">Show Account Info Form</a></p>
        
        <p><a href="/1q2w3e4r5t/activity">Show Activity Info Form</a></p>
        
        <p><a href="/1q2w3e4r5t/approve">Show Approve Form</a></p>
        
        <p><a href="/1q2w3e4r5t/reject">Show Reject Form</a></p>